"use client"

import { PopoverContent } from "@/components/ui/popover"
import { APP_NAME } from "@/lib/config"
import Image from "next/image"

export function PopoverContentStorage() {
  return (
    <PopoverContent
      className="w-[300px] overflow-hidden rounded-xl p-0"
      side="top"
      align="start"
    >
      <Image
        src="/banner_forest.jpg"
        alt={`calm paint generated by ${APP_NAME}`}
        width={300}
        height={128}
        className="h-32 w-full object-cover"
      />
      <div className="p-4">
        <p className="text-primary mb-1 text-base font-medium">
          Storage not configured
        </p>
        <p className="text-muted-foreground text-sm">
          To upload files and attachments, you need to configure a Supabase storage bucket in settings.
        </p>
      </div>
    </PopoverContent>
  )
}
